spring:
  datasource:
    url: jdbc:mysql://localhost:3306/app?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: xxxxxxxx
  jpa:
    hibernate:
      ddl-auto: update  # 可选: create, update, validate
    show-sql: true      # 可选: 打印 SQL
    database-platform: org.hibernate.dialect.MySQL8Dialect

  ai:
    openai:
        api-key: Xxxxxxxxx

logging:
  level:
    org.example.server.dao: debug
    org.mybatis: debug